runtime: nodejs20

handlers:
  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
env_variables:
  PATCHRSS_HOST: patchrss.dt.r.appspot.com
